version: "3"
services:
  search-restaurants:
    container_name: search-restaurants
    restart: always
    build: ./search-restaurants
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  nodemailer-service:
    container_name: nodemailer-service
    restart: always
    build: ./nodemailer-service
    ports:
      - "3010:3010"
    links:
      - mongo
    depends_on:
      - mongo
  order-service:
    container_name: order-service
    restart: always
    build: ./order-service
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
  aggregator-service:
    container_name: aggregator-service
    restart: always
    build: ./aggregator-service
    ports:
      - "3002:3002"
    links:
      - mongo
    depends_on:
      - mongo
  rabitmq-service:
    container_name: rabitmq-service
    restart: always
    build: ./rabitmq-service
    ports:
      - "3005:3005"
    links:
      - mongo
    depends_on:
      - mongo
  api-gateway:
    container_name: api-gateway
    restart: always
    build: ./api-gateway
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
