http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  restaurant-orders-api:
    host: localhost
    paths: "/orders/"
  restaurant-single-order-api:
    host: localhost
    paths: "/order/"

serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  restaurant-order-service-endpoints:
    url: "http://localhost:3001/"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  restaurant-orders-pipeline:
    apiEndpoints:
      - restaurant-orders-api
    policies:
    #  - key-auth:
      - proxy:
          - action:
              serviceEndpoint: restaurant-order-service-endpoints
              changeOrigin: true
  restaurant-single-order-pipeline:
    apiEndpoints:
    - restaurant-single-order-api
    policies:
      - proxy:
          - action:
              serviceEndpoint: restaurant-order-service-endpoints
              changeOrigin: true
